Repository Tutor-Talk/BE, pull requests merged in 2025-05, with the labels that each got.

#1 FEAT: 회원가입/로그인 기능 추가
  build.gradle
  compose.yaml
  src/main/java/org/tutortalk/be/domain/user/controller/AuthController.java
  src/main/java/org/tutortalk/be/domain/user/dto/LoginRequest.java
  src/main/java/org/tutortalk/be/domain/user/dto/LoginResponse.java
  src/main/java/org/tutortalk/be/domain/user/dto/SignupRequest.java
  src/main/java/org/tutortalk/be/domain/user/entity/User.java
  src/main/java/org/tutortalk/be/domain/user/repository/UserRepository.java
  src/main/java/org/tutortalk/be/domain/user/service/AuthService.java
  src/main/java/org/tutortalk/be/domain/user/service/impl/AuthServiceImpl.java
  src/main/java/org/tutortalk/be/global/config/JwtAuthenticationFilter.java
  src/main/java/org/tutortalk/be/global/config/JwtProvider.java
  src/main/java/org/tutortalk/be/global/config/SecurityConfig.java
Labels: feature

#3 Feature: 복지 서비스 알림 기능 구현 (#2)
  build.gradle
  src/main/java/org/tutortalk/be/domain/user/entity/User.java
  src/main/java/org/tutortalk/be/domain/welfare/config/WebClientConfig.java
  src/main/java/org/tutortalk/be/domain/welfare/config/WelfareApiClient.java
  src/main/java/org/tutortalk/be/domain/welfare/controller/WelfareController.java
  src/main/java/org/tutortalk/be/domain/welfare/dto/ServiceListDto.java
  src/main/java/org/tutortalk/be/domain/welfare/dto/WelfareListDto.java
  src/main/java/org/tutortalk/be/domain/welfare/dto/WelfareResponseDto.java
  src/main/java/org/tutortalk/be/domain/welfare/entity/Welfare.java
  src/main/java/org/tutortalk/be/domain/welfare/repository/WelfareRepository.java
  src/main/java/org/tutortalk/be/domain/welfare/service/WelfareService.java
  src/main/java/org/tutortalk/be/domain/welfare/util/AgeCategoryMapper.java
  src/main/java/org/tutortalk/be/global/config/JwtAuthenticationFilter.java
  src/main/java/org/tutortalk/be/global/config/SecurityConfig.java
  src/main/java/org/tutortalk/be/global/util/CustomUserDetailsService.java
  src/main/java/org/tutortalk/be/global/util/UserPrincipal.java
  src/main/resources/application.yml
Labels: feature

#5 Fix: GitHub Actions 워크플로우에서 port 삭제
  .github/workflows/deploy.yml
Labels: fix

#6 Fix: GitHub Actions 워크플로우에서 EC2_IP 추가
  .github/workflows/deploy.yml
Labels: fix

#8 Bug: 워크플로우에 .env 파일 생성 단계 추가
  .github/workflows/deploy.yml
Labels: bug

#12 Fix/login system
  build.gradle
  src/main/java/org/tutortalk/be/domain/user/dto/SignupRequest.java
  src/main/java/org/tutortalk/be/domain/user/entity/User.java
  src/main/java/org/tutortalk/be/domain/user/service/impl/AuthServiceImpl.java
  src/main/resources/application.yml
Labels: fix

#14 Feature/contents
  .gitignore
  build.gradle
  src/main/java/org/tutortalk/be/domain/contents/controller/ContentController.java
  src/main/java/org/tutortalk/be/domain/contents/entity/Content.java
  src/main/java/org/tutortalk/be/domain/contents/repository/ContentRepository.java
  src/main/java/org/tutortalk/be/domain/contents/service/ContentService.java
  src/main/java/org/tutortalk/be/global/config/AwsS3Config.java
  src/main/java/org/tutortalk/be/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: feature

#15 FIX: application.yml 수정 백엔드 배포 환경에 맞춰 OAuth2 리디렉트 방식 및 CORS 수정
  src/main/java/org/tutortalk/be/global/config/SecurityConfig.java
  src/main/java/org/tutortalk/be/global/oauth/GoogleOAuth2SuccessHandler.java
  src/main/resources/application.yml
Labels: fix

#16 fix: 도메인 연결 및 SSL 설정 완료
  compose.yaml
  src/main/resources/application.yml
Labels: fix
